name: Deploy .NET Core App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and publish
        run: |
          dotnet build -c Release
          dotnet publish -c Release -r linux-x64 --self-contained false
        
      - name: Upload artifact to server
        uses: appleboy/scp-action@master
        with:
          host: 146.190.220.28
          username: root
          password: qpwoeiruTY3164@
          source: SensorizMonitoring/bin/Release/net8.0/linux-x64/publish/
          target: /home/artifact/

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 146.190.220.28
          username: root
          password: qpwoeiruTY3164@
          script: |
            mkdir -p /home/monitoring
            rm -rf /home/monitoring/[^appsettings.json]
            cp -r /home/artifact/SensorizMonitoring/bin/Release/net8.0/linux-x64/* /home/monitoring/
            rm -rf /home/artifact/SensorizMonitoring/bin/Release/net8.0/linux-x64/*
            pm2 restart all
