name: Deploy .NET Core App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload artifact to server
        uses: appleboy/scp-action@master
        with:
          host: 146.190.220.28
          username: root
          password: qpwoeiruTY3164@
          source: SensorizMonitoring/bin/Release/net8.0/linux-x64/
          destination: /home/artifact/

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 146.190.220.28
          username: root
          password: qpwoeiruTY3164@
          script: |
            mkdir -p /home/monitoring
            rm -rf /home/monitoring/* !(/home/monitoring/appsettings.json)
            cp -r /home/artifact/* /home/monitoring/
            rm -rf /home/artifact/*
            pm2 restart all
