name: Deploy .NET Core App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sensoriz-monitoring
          path: SensorizMonitoring/bin/Release/net8.0/linux-x64/

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: sensoriz-monitoring

      - name: Deploy to server
        uses: digitalocean/ssh@v1
        with:
          host: 146.190.220.28
          username: root
          password: qpwoeiruTY3164@
          script: |
            mkdir -p /home/monitoring
            cp -r sensoriz-monitoring/* /home/monitoring/
            pm2 restart all
